docker rm -f $WA_OPENSOURCE_APP_NAME
docker build -t $WA_OPENSOURCE_APP_NAME:latest -t $WA_OPENSOURCE_APP_NAME:$WA_OPENSOURCE_APP_VERSION .
docker run -d --restart=always \-p $WA_OPENSOURCE_EXP_PORT:$WA_OPENSOURCE_PORT --name $WA_OPENSOURCE_APP_NAME $WA_OPENSOURCE_APP_NAME:$WA_OPENSOURCE_APP_VERSION